import type { ComponentType } from 'react';

/**
 * A custom entity is any host-application object, expressed as JSON.
 *
 * MagicChat treats this as OPAQUE DATA. It reads `type` (to look up renderers)
 * and nothing else — never `properties`, whose schema it does not know.
 */
export interface CustomEntity<P = object> {
  type: string;
  properties: P;
}

/** Props given to a `composer` renderer (the chip shown before sending). */
export interface CustomEntityComposerProps<E extends CustomEntity = CustomEntity> {
  /** The complete JSON entity, exactly as the host provided it. */
  entity: E;
  /** MagicChat's own id for this attachment. See `AttachedEntity`. */
  instanceId: string;
  /** Detach this entity from the composer before sending. */
  remove: () => void;
}

/** Props given to a `message` renderer (inside a sent message body). */
export interface CustomEntityMessageProps<E extends CustomEntity = CustomEntity> {
  /** The complete JSON entity, exactly as the host provided it. */
  entity: E;
  /** Read-only context: the message this entity was sent with. */
  message: ChatMessage;
}

/**
 * How the host renders one entity type in each of MagicChat's two surfaces.
 *
 * Both renderers are plain components, so the shorthand
 * `composer: ({ entity }) => <CarChip entity={entity} />` works as-is.
 */
export interface CustomEntityTypeDefinition<E extends CustomEntity = CustomEntity> {
  composer: ComponentType<CustomEntityComposerProps<E>>;
  message: ComponentType<CustomEntityMessageProps<E>>;
  /** Human-readable name, used in the drop overlay and for accessibility. */
  label?: (entity: E) => string;
  /**
   * Optional stable identity, letting the host opt into de-duplication in the
   * composer. MagicChat cannot derive this itself — it does not know the schema.
   */
  getId?: (entity: E) => string;
}

/**
 * Registry keyed by `CustomEntity.type`.
 *
 * The entity generic is erased to `any` here so that definitions for different
 * entity types can live in one object. Hosts keep their typing by writing
 * renderers as typed components (see the demo's `entityRenderers.tsx`).
 */
export type CustomEntityTypeRegistry = Record<string, CustomEntityTypeDefinition<any>>;

/**
 * An entity attached to the composer.
 *
 * `instanceId` is generated by MagicChat. It deliberately does NOT come from
 * `properties.id`: MagicChat does not know the entity schema, so it cannot
 * assume such a field exists. React keys need a stable id, so it makes its own.
 */
export interface AttachedEntity {
  instanceId: string;
  entity: CustomEntity;
}

export interface ChatMessage {
  id: string;
  author: 'me' | 'them';
  authorName: string;
  text: string;
  /** Entities attached to this message, rendered with their `message` renderer. */
  entities: CustomEntity[];
  sentAt: string;
}

/** Why a drag ended without the entities being dropped on MagicChat. */
export type CustomEntityDragCancelReason = 'released-outside' | 'cancelled';

/** Fallback renderer for an entity whose `type` is not in the registry. */
export interface UnknownEntityProps {
  entity: CustomEntity;
  surface: 'composer' | 'message';
}

/* ------------------------------------------------------------------ *
 * Debug instrumentation
 *
 * Purely diagnostic: it lets a host display what the drop target is
 * doing right now. Nothing in the mechanism depends on it, and if no
 * debug callback is supplied none of it is computed.
 * ------------------------------------------------------------------ */

/**
 * One arming of `dragCustomEntities` permits at most one drop.
 *
 *   idle --(entities appear)--> armed --(release/cancel)--> spent
 *     ^                                                      |
 *     +---------------- (host clears the array) -------------+
 */
export type CustomEntityDragLatchState = 'idle' | 'armed' | 'spent';

/** The listeners the drop target attaches while a drag is armed. */
export type CustomEntityDropListenerName =
  | 'pointermove'
  | 'pointerup'
  | 'pointercancel'
  | 'keydown'
  | 'blur';

export interface CustomEntityDropListenerStatus {
  /** Currently registered on `document` (or `window`, for `blur`). */
  attached: boolean;
  /** How many times it has fired during the current arming. */
  fired: number;
}

export interface CustomEntityDropDebugEvent {
  name: string;
  detail?: string;
  at: number;
}

/** A snapshot of the drop target's internals, for display. */
export interface CustomEntityDropDebug {
  latch: CustomEntityDragLatchState;
  /** True while listeners are attached — i.e. only while armed. */
  listening: boolean;
  listeners: Record<CustomEntityDropListenerName, CustomEntityDropListenerStatus>;
  /** Length of `dragCustomEntities`. */
  entityCount: number;
  /** The pointer this gesture is locked to; other pointers are ignored. */
  pointerId: number | null;
  pointerType: string | null;
  buttons: number | null;
  pointer: { x: number; y: number } | null;
  /** The most recent `document.elementFromPoint` result. */
  hit: { element: string; insideDropZone: boolean } | null;
  isPointerOver: boolean;
  lastOutcome: 'dropped' | CustomEntityDragCancelReason | null;
  /** Most recent discrete events, newest first. Moves are counted, not logged. */
  recentEvents: CustomEntityDropDebugEvent[];
}

export interface MagicChatProps {
  /** How to render each supported entity type. See `CustomEntityTypeDefinition`. */
  customEntityTypes: CustomEntityTypeRegistry;

  /**
   * Entities the host is currently dragging. Non-empty means "a drag is in
   * flight"; MagicChat then watches for the pointer release.
   *
   * CONTRACT: the host must clear this back to empty before starting the next
   * drag. MagicChat allows at most one drop per non-empty period.
   */
  dragCustomEntities?: CustomEntity[];

  /** The entities were dropped on MagicChat. The host should clear the array. */
  onDragCustomEntitiesConsumed?: (entities: CustomEntity[]) => void;

  /**
   * The drag ended without a drop. The host should clear the array.
   *
   * Worth handling even if you already clear on your own `pointerup`: on
   * `pointercancel` (common on touch) or when the pointer is released outside
   * the window, your `pointerup` may never fire.
   */
  onCustomEntityDragCancelled?: (reason: CustomEntityDragCancelReason) => void;

  initialMessages?: ChatMessage[];
  onSendMessage?: (message: ChatMessage) => void;
  renderUnknownEntity?: ComponentType<UnknownEntityProps>;

  /**
   * Diagnostics only. Called with a snapshot of the drop target's internals,
   * coalesced to one call per animation frame. Omit it and nothing is computed.
   */
  onDebugChange?: (debug: CustomEntityDropDebug) => void;
}

/** Imperative API, for attaching entities without a drag (e.g. a button). */
export interface MagicChatHandle {
  attachEntities: (entities: CustomEntity[]) => void;
  clearComposer: () => void;
  focus: () => void;
}
