import type { ComponentType } from 'react';

/**
 * A custom entity is any host-application object, expressed as JSON.
 *
 * MagicChat treats this as OPAQUE DATA. It reads `type` (to look up renderers)
 * and nothing else — never `properties`, whose schema it does not know.
 */
export interface CustomEntity<P = object> {
  type: string;
  properties: P;
}

/** Props given to a `composer` renderer (the chip shown before sending). */
export interface CustomEntityComposerProps<E extends CustomEntity = CustomEntity> {
  /** The complete JSON entity, exactly as the host provided it. */
  entity: E;
  /** MagicChat's own id for this attachment. See `AttachedEntity`. */
  instanceId: string;
  /**
   * Detach this entity from the composer before sending.
   *
   * You do NOT have to call this, and a chip should not normally draw its own
   * ×: MagicChat wraps every composer renderer in a chip shell that already
   * carries one. Detaching is MagicChat state, so MagicChat offers the control.
   * This is the escape hatch for a host that wants a second one of its own
   * (a "clear" inside a wider card, say); ignoring it is the common case.
   */
  remove: () => void;
}

/** Props given to a `message` renderer (inside a sent message body). */
export interface CustomEntityMessageProps<E extends CustomEntity = CustomEntity> {
  /** The complete JSON entity, exactly as the host provided it. */
  entity: E;
  /** Read-only context: the message this entity was sent with. */
  message: ChatMessage;
}

/**
 * How the host renders one entity type in each of MagicChat's two surfaces.
 *
 * Both renderers are plain components, so the shorthand
 * `composer: ({ entity }) => <CarChip entity={entity} />` works as-is.
 */
export interface CustomEntityComponentDefinition<E extends CustomEntity = CustomEntity> {
  composer: ComponentType<CustomEntityComposerProps<E>>;
  message: ComponentType<CustomEntityMessageProps<E>>;
  /** Human-readable name, used in the drop overlay and for accessibility. */
  label?: (entity: E) => string;
  /**
   * Optional stable identity, letting the host opt into de-duplication in the
   * composer. MagicChat cannot derive this itself — it does not know the schema.
   */
  getId?: (entity: E) => string;
}

/**
 * Registry keyed by `CustomEntity.type`.
 *
 * The entity generic is erased to `any` here so that definitions for different
 * entity types can live in one object. Hosts keep their typing by writing
 * renderers as typed components (see the demo's `entityRenderers.tsx`).
 */
export type CustomEntityComponentRegistry = Record<string, CustomEntityComponentDefinition<any>>;

/**
 * An entity attached to the composer.
 *
 * `instanceId` is generated by MagicChat. It deliberately does NOT come from
 * `properties.id`: MagicChat does not know the entity schema, so it cannot
 * assume such a field exists. React keys need a stable id, so it makes its own.
 */
export interface AttachedEntity {
  instanceId: string;
  entity: CustomEntity;
}

export interface ChatMessage {
  id: string;
  author: 'me' | 'them';
  authorName: string;
  text: string;
  /** Entities attached to this message, rendered with their `message` renderer. */
  entities: CustomEntity[];
  sentAt: string;
}

/** Why a drag ended without the entities being dropped on MagicChat. */
export type CustomEntityDragCancelReason = 'released-outside' | 'cancelled';

/** Fallback renderer for an entity whose `type` is not in the registry. */
export interface UnknownEntityProps {
  entity: CustomEntity;
  surface: 'composer' | 'message';
}

/* ------------------------------------------------------------------ *
 * Debug instrumentation
 *
 * Purely diagnostic: it lets a host display what the drop target is
 * doing right now. Nothing in the mechanism depends on it, and if no
 * debug callback is supplied none of it is computed.
 * ------------------------------------------------------------------ */

/**
 * One call to `startCustomEntityDrag` permits at most one drop.
 *
 *   idle --(startCustomEntityDrag, button held)--> armed
 *     ^                                              |
 *     +------------ (release / cancel) --------------+
 *
 * Self-clearing, and there is no third state. The old prop-driven design needed
 * a `spent` state because its arming signal outlived the gesture; an arming that
 * is a function call cannot, so the gesture returns to `idle` on its own.
 */
export type CustomEntityDragLatchState = 'idle' | 'armed';

/** The listeners the drop target attaches *for the duration of a gesture*. */
export type CustomEntityDropListenerName =
  | 'pointermove'
  | 'pointerup'
  | 'pointercancel'
  | 'keydown'
  | 'blur';

export interface CustomEntityDropListenerStatus {
  /** Currently registered on `document` (or `window`, for `blur`). */
  attached: boolean;
  /** How many times it has fired during the current arming. */
  fired: number;
}

export interface CustomEntityDropDebugEvent {
  name: string;
  detail?: string;
  at: number;
}

/** A snapshot of the drop target's internals, for display. */
export interface CustomEntityDropDebug {
  latch: CustomEntityDragLatchState;
  /** Gesture listeners currently attached — i.e. only while armed. */
  listening: boolean;
  listeners: Record<CustomEntityDropListenerName, CustomEntityDropListenerStatus>;
  /** Size of the armed payload. */
  entityCount: number;
  /**
   * The pointer the always-on tracker currently sees held, if any.
   *
   * This is the state `startCustomEntityDrag` consults, so it is also the
   * answer to "why was my drag refused?" — `null` here means no button is down.
   */
  pointerDown: { pointerId: number; pointerType: string } | null;
  /**
   * How many `startCustomEntityDrag` calls have been refused, cumulatively —
   * almost always because no button was held. A non-zero counter means a host
   * is announcing drags outside a real press.
   */
  refusedStarts: number;
  /** The pointer this gesture is locked to; other pointers are ignored. */
  pointerId: number | null;
  pointerType: string | null;
  buttons: number | null;
  pointer: { x: number; y: number } | null;
  /** The most recent `document.elementFromPoint` result. */
  hit: { element: string; insideDropZone: boolean } | null;
  isPointerOver: boolean;
  lastOutcome: 'dropped' | CustomEntityDragCancelReason | null;
  /** Most recent discrete events, newest first. Moves are counted, not logged. */
  recentEvents: CustomEntityDropDebugEvent[];
}

export interface MagicChatProps {
  /** How to render each supported entity type. See `CustomEntityComponentDefinition`. */
  customEntityComponents: CustomEntityComponentRegistry;

  /**
   * The entities were dropped on MagicChat and are now in the composer.
   *
   * Purely informational — the host has nothing it must do in response. It is
   * the right place to tear down host-side drag chrome such as a drag ghost.
   */
  onDragCustomEntitiesConsumed?: (entities: CustomEntity[]) => void;

  /**
   * The drag ended without a drop.
   *
   * Worth handling even if you already tear down on your own `pointerup`: on
   * `pointercancel` (common on touch) or when the pointer is released outside
   * the window, your `pointerup` may never fire — and your drag ghost would be
   * left on screen.
   */
  onCustomEntityDragCancelled?: (reason: CustomEntityDragCancelReason) => void;

  initialMessages?: ChatMessage[];
  onSendMessage?: (message: ChatMessage) => void;
  renderUnknownEntity?: ComponentType<UnknownEntityProps>;

  /**
   * Diagnostics only. Called with a snapshot of the drop target's internals,
   * synchronously and unthrottled (see DECISIONS.md §13 for why it is not
   * coalesced into a frame). Omit it and nothing is computed.
   */
  onDebugChange?: (debug: CustomEntityDropDebug) => void;
}

/**
 * Imperative API. This is how a drag is announced.
 *
 * `startCustomEntityDrag` is the host's whole side of the drag contract, and it
 * lives here rather than in a prop because "a button is down on one of my
 * objects right now" is an event, not a value. See DECISIONS.md §15.
 */
export interface MagicChatHandle {
  /**
   * Announce a drag of `entities` and arm the drop target.
   *
   * MUST be called while a button is physically held — from a `pointerdown`
   * handler, or later inside the same held gesture (a long-press or a
   * drag-threshold delay is fine). With no button down the call is refused,
   * returns `false` and changes nothing.
   *
   * Calling it again while armed replaces the payload without re-arming, so a
   * selection can grow mid-drag. Returns whether the target is armed.
   */
  startCustomEntityDrag: (entities: CustomEntity[]) => boolean;
  /**
   * Abandon an armed drag. Silent — neither resolve callback fires, because the
   * host asked for it and therefore already knows.
   */
  cancelCustomEntityDrag: () => void;
  /** Attach entities without a drag at all — e.g. a "Send to chat" button. */
  attachEntities: (entities: CustomEntity[]) => void;
  clearComposer: () => void;
  focus: () => void;
}
